//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Calendar defines model for Calendar.
type Calendar struct {
	// AliasCode URL上の識別子
	AliasCode string `json:"aliasCode"`

	// CoverImageUrl カバー画像 URL
	CoverImageUrl *string `json:"coverImageUrl,omitempty"`

	// Description カレンダーの概要文
	Description *string `json:"description,omitempty"`

	// Id カレンダーの一意識別子
	Id string `json:"id"`

	// SnsLinks 関連 SNS リンク
	SnsLinks *SNSLinks `json:"snsLinks,omitempty"`

	// Title カレンダー名（グループ/アイドル名）
	Title string `json:"title"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Detail エラー詳細メッセージ
	Detail string `json:"detail"`

	// Instance リクエストパス
	Instance *string `json:"instance,omitempty"`

	// Status HTTP ステータスコード
	Status int `json:"status"`

	// Title エラー概要
	Title string `json:"title"`

	// Type エラー種別 URI (RFC 7807)
	Type string `json:"type"`
}

// Event defines model for Event.
type Event struct {
	// AllDay 終日イベントフラグ
	AllDay bool `json:"allDay"`

	// Description イベント詳細・物販情報・チケット情報
	Description *string `json:"description,omitempty"`

	// EndAt 終了日時 (ISO8601)
	EndAt time.Time `json:"endAt"`

	// Id イベント一意識別子
	Id string `json:"id"`

	// ImageUrls 添付画像 URL リスト
	ImageUrls *[]string `json:"imageUrls,omitempty"`

	// Location 会場・開催場所
	Location *string `json:"location"`

	// StartAt 開始日時 (ISO8601)
	StartAt time.Time `json:"startAt"`

	// Timezone タイムゾーン（原則 Asia/Tokyo）
	Timezone string `json:"timezone"`

	// Title イベント名（公演・物販・生誕祭等）
	Title string `json:"title"`

	// Url 関連 URL（チケット・詳細ページ）
	Url *string `json:"url"`

	// Uuid イベント UUID
	Uuid *string `json:"uuid,omitempty"`
}

// EventListResponse defines model for EventListResponse.
type EventListResponse struct {
	Calendar   Calendar   `json:"calendar"`
	Events     []Event    `json:"events"`
	Pagination Pagination `json:"pagination"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
	Version   string    `json:"version"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	CurrentPage int `json:"currentPage"`
	TotalCount  int `json:"totalCount"`
	TotalPages  int `json:"totalPages"`
}

// SNSLinks 関連 SNS リンク
type SNSLinks struct {
	Instagram *string `json:"instagram,omitempty"`
	Twitter   *string `json:"twitter,omitempty"`
	Website   *string `json:"website,omitempty"`
}

// CalendarIdParam defines model for CalendarIdParam.
type CalendarIdParam = string

// BadGatewayError defines model for BadGatewayError.
type BadGatewayError = ErrorResponse

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorResponse

// GetCalendarEventsParams defines parameters for GetCalendarEvents.
type GetCalendarEventsParams struct {
	// Year 取得対象年（例: 2026）
	Year *int `form:"year,omitempty" json:"year,omitempty"`

	// Month 取得対象月 (1-12)
	Month *int `form:"month,omitempty" json:"month,omitempty"`

	// Page ページ番号
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCalendar request
	GetCalendar(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCalendarEvents request
	GetCalendarEvents(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCalendarEventsICS request
	GetCalendarEventsICS(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCalendar(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCalendarRequest(c.Server, calendarId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCalendarEvents(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCalendarEventsRequest(c.Server, calendarId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCalendarEventsICS(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCalendarEventsICSRequest(c.Server, calendarId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCalendarRequest generates requests for GetCalendar
func NewGetCalendarRequest(server string, calendarId CalendarIdParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "calendarId", runtime.ParamLocationPath, calendarId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/calendars/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCalendarEventsRequest generates requests for GetCalendarEvents
func NewGetCalendarEventsRequest(server string, calendarId CalendarIdParam, params *GetCalendarEventsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "calendarId", runtime.ParamLocationPath, calendarId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/calendars/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Year != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "year", runtime.ParamLocationQuery, *params.Year); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Month != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "month", runtime.ParamLocationQuery, *params.Month); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCalendarEventsICSRequest generates requests for GetCalendarEventsICS
func NewGetCalendarEventsICSRequest(server string, calendarId CalendarIdParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "calendarId", runtime.ParamLocationPath, calendarId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/calendars/%s/events.ics", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCalendarWithResponse request
	GetCalendarWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarResponse, error)

	// GetCalendarEventsWithResponse request
	GetCalendarEventsWithResponse(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*GetCalendarEventsResponse, error)

	// GetCalendarEventsICSWithResponse request
	GetCalendarEventsICSWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarEventsICSResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type GetCalendarResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Calendar
	JSON400      *BadRequestError
	JSON404      *NotFoundError
	JSON500      *InternalServerError
	JSON502      *BadGatewayError
}

// Status returns HTTPResponse.Status
func (r GetCalendarResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCalendarResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCalendarEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventListResponse
	JSON400      *BadRequestError
	JSON404      *NotFoundError
	JSON500      *InternalServerError
	JSON502      *BadGatewayError
}

// Status returns HTTPResponse.Status
func (r GetCalendarEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCalendarEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCalendarEventsICSResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequestError
	JSON404      *NotFoundError
	JSON500      *InternalServerError
	JSON502      *BadGatewayError
}

// Status returns HTTPResponse.Status
func (r GetCalendarEventsICSResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCalendarEventsICSResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCalendarWithResponse request returning *GetCalendarResponse
func (c *ClientWithResponses) GetCalendarWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarResponse, error) {
	rsp, err := c.GetCalendar(ctx, calendarId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCalendarResponse(rsp)
}

// GetCalendarEventsWithResponse request returning *GetCalendarEventsResponse
func (c *ClientWithResponses) GetCalendarEventsWithResponse(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*GetCalendarEventsResponse, error) {
	rsp, err := c.GetCalendarEvents(ctx, calendarId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCalendarEventsResponse(rsp)
}

// GetCalendarEventsICSWithResponse request returning *GetCalendarEventsICSResponse
func (c *ClientWithResponses) GetCalendarEventsICSWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarEventsICSResponse, error) {
	rsp, err := c.GetCalendarEventsICS(ctx, calendarId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCalendarEventsICSResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParseGetCalendarResponse parses an HTTP response from a GetCalendarWithResponse call
func ParseGetCalendarResponse(rsp *http.Response) (*GetCalendarResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCalendarResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Calendar
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGatewayError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetCalendarEventsResponse parses an HTTP response from a GetCalendarEventsWithResponse call
func ParseGetCalendarEventsResponse(rsp *http.Response) (*GetCalendarEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCalendarEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGatewayError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetCalendarEventsICSResponse parses an HTTP response from a GetCalendarEventsICSWithResponse call
func ParseGetCalendarEventsICSResponse(rsp *http.Response) (*GetCalendarEventsICSResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCalendarEventsICSResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGatewayError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// カレンダー基本情報の取得
	// (GET /api/v1/calendars/{calendarId})
	GetCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarIdParam)
	// イベント一覧の取得 (JSON)
	// (GET /api/v1/calendars/{calendarId}/events)
	GetCalendarEvents(w http.ResponseWriter, r *http.Request, calendarId CalendarIdParam, params GetCalendarEventsParams)
	// iCalendar (.ics) 形式でのイベント配信
	// (GET /api/v1/calendars/{calendarId}/events.ics)
	GetCalendarEventsICS(w http.ResponseWriter, r *http.Request, calendarId CalendarIdParam)
	// ヘルスチェック
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCalendar operation middleware
func (siw *ServerInterfaceWrapper) GetCalendar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", r.PathValue("calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendar(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCalendarEvents operation middleware
func (siw *ServerInterfaceWrapper) GetCalendarEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", r.PathValue("calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCalendarEventsParams

	// ------------- Optional query parameter "year" -------------

	err = runtime.BindQueryParameter("form", true, false, "year", r.URL.Query(), &params.Year)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		return
	}

	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameter("form", true, false, "month", r.URL.Query(), &params.Month)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendarEvents(w, r, calendarId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCalendarEventsICS operation middleware
func (siw *ServerInterfaceWrapper) GetCalendarEventsICS(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", r.PathValue("calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendarEventsICS(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/calendars/{calendarId}", wrapper.GetCalendar)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/calendars/{calendarId}/events", wrapper.GetCalendarEvents)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/calendars/{calendarId}/events.ics", wrapper.GetCalendarEventsICS)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RZa1MTWRr+K729WzVaG9IhAmK+OXgZdhmGIlBbtVOWdUgOobVvdp+gjJWqdLdIuC2u",
	"paCuVeCFiyhBF13RRPgxJ92ET/yFrXO6k3QnHYK7M36Zb9Dp897f533O27fZhCwqsgQlpLGx26wCVCBC",
	"BFX6Xw8QoJQEam9ygDwnj5JQS6i8gnhZYmPsEC/CIRVCxpp8c7g4i43X2HyDzR1sZrFZxHq+vPXIyq1a",
	"W/eOijkg8EC7mpCTEGf10t5sjOEFfhRelUdH+QQPhKPiNBtieSJXAWiMDbESECEbYxNVM9gQq8IbaV6F",
	"STaG1DQMsVpiDIqAmAZvAVERyAG/XDbEogmFPNeQykspNpPJEDmaIksapI5+D5KXAYI3wcRFVZVV8igh",
	"SwhKiPwJFEXgE4D4zF3TiOO3PWr/pMJRNsb+katFknN+1TgqbdDV5Oj1BxAbz7FpYnMJG5+wmcPmJomb",
	"uXJUzFVie1ScxvoG1vOH2Sel/WfY2MDmKxrdPawvY327VHhorz+yXk7b/3pvv3x6sLzKZkLEpUF4Iw01",
	"9K1dMjexsU3MdF36J7X3GTHZ2C/tzttbL4iBvRKCqgSEOFTHofrN4/6BBvoeNovW3clDc6MaV2Jbv4wu",
	"yWkp+c2tqusfN8M0pF9oAD9hfa68Nov1l1ifxcY01jexfoclslw13salLa3KClQR71Q6bcIeOQkbm3l4",
	"sK+0O+NtWjb0FU0VYhPyOFR7RZCCw6rQKJ96RwJ+8KBgmQvM8GCfT8EYQooW4ziAEEiMiSR0YcSLEKkQ",
	"AkUJJ2SRU9IjAp+4WkEETqOHw9eUFBtiR2VVBIiNsWmVD7LPZ87tVrHP22tGeU23F6f8YejjL138A9bz",
	"2HiJzcf0QA6bBWvqs118QBJkvMPGLjZXaYG9xvo61h/jrBFkEZ88iSGl3ax9ZyE4Kx1dHWe6g0RrktbH",
	"S9e1VkUZ748772VCLOKRAFtaZN2bPyrmsPGWeEd8XOIIjJFwTGPzNf15OiBmATjshfOfSTRCngKt2HOl",
	"ek4euQYTiFjqb6WGKk9CBPjAEnSbvPxq5+D9W4pKJjYKtLV2fTYP0EpjKpXGfOev/++Ym0BjJBkxowQo",
	"GFliKoAdDsy0pCEgJYKi24iXxiefKRxQeG68navYonG8NA4EPnmVRqwx9QigtNao6YehoQGGarnrgDGt",
	"1h2aQ1/COiIdVbG8hGAKqseWhxtUp2F8pg9CTU6rCcj0y4ihkBpksPOgqdyDjbyVW2WGB3uZU4OXepiz",
	"3ZGzpwOhQ0iLPIGLcBKOc5DUiMZJMmobdTUfjxB15Uh/rXhdjWqoUlyBZTnuDol60BUugIlGDw8+GPbS",
	"qh9IHhKfjbde90aBoMGqthFZFiCQTgBoNbGVci8cTL8q//uVbU5aK++wWcCmTuCKMJCc89AX1m4u2sn8",
	"lXIUh5fM2Bub9oenWH+N9TVrMld+NudIxMZ9K79sL37B+hIdW80QD0rJ8ygwEqXPd+2lVfuxwZzqjf/U",
	"3RVp9+c4Gol2tUW626KdQ+3RWCQSi0T+HDkXi0S8eU0CBNvI0Dg52taidBzOtkfPdHR2nQ2EWt4deQEt",
	"Z38slAqPagOPod1O+pxQXQRFeqbV4HIfAFUFE+R/QXb4R6O+UvGJtfIem4XDxVnLeGOtvLensz5HAtJJ",
	"mHZaEMAIecFh1UGYoqKgzBFF67MnzRxN2Ndnjjz/RZYCQWKfpnAFG3vUp52jYs76x7I1PcWc13jADcnX",
	"J+T6gVT7JVhbE5yrlYozA63JN2TmV9qK/PFgubz58GB162Brul7pjxcvn6eDkPF2zlFxJTglDWalg0jV",
	"4eLzw+wLUlpkJnvaGZuFStc/ccZbvT0V0ER84jpE4TGoyrwEtfA1hRNhCpBxd5LKSKdb9RUzPNx7waf6",
	"XPfZrs6OM9E2MJJItsHRSHsb6a+2rrPd58gj8uRkdMGDzrQ+KwgTqoCup3iaInYfr6HmZCLhIdPHMakq",
	"6SYwN165UVeb/NibAZ0bAZ2ugBQvVXv9OBEDtTfrA1V1oGqXT3BQWH6AQEBjzWNSoxi1pMrXm7WuhoCo",
	"+F+uYkJ0qL3LwYS/nxgOxqGquSHxIHQ4Eo60LJrqFK/I8FoYFIkBXwbqKiOtqlBCAyAFfba0B7InGQGh",
	"R047BKH2brTpy0Su1kpwfa49JvnE+AwIcrR6EWiGMfH+OB1f5g42tkkJ+WJBCW7K3RI1gkz1Z3qNa32X",
	"RDd5hKAaLOyWI4SA6bFCbsIRjUewiUXEBi/qBdZOXZgylMqPyseswuiN/BXW84E7MZd6GfethUVrbwmb",
	"BXvjsf150ZpbJNQpqzODF+NDzPmBXgbrM9jIYX2H4SvQwpwK8wntNEMXQktYXzucnC/tPyN0y5gtF74c",
	"Ti1gcwmbW9jYwsZHIsbhYQKfgG4ju0u1H3uHWHemVEMiK1By+HpYVlOce0jjyLu1uchWWDbj3pGq1n2v",
	"8skUJFo9DVbpzEyIJfKBwrMx9kw4Ej5DYQiN0fJpvOPcrq39MuSNFAxgH/bclJV/gvWH2JjD+nJdsHsv",
	"kKFY2aIwtQUk3anlyfXP2HcyQm+0DpXIkXttVnduMzirO+wNZ/V4f7xa/858r+XRT3tJY1DM6E2yMfYy",
	"RD01CPauWH8OxvTaK1z9CjZzpW51GY1EfrUFVW2CtdxNOVFznLdz96yZZZLgDseYIB1Vo7n6zSQ919H6",
	"nH8plwmxnSfRFrRmpGejJ7LUtxamW7a0KAJ1ImAtsvzZfvrG7W8974SGYApIkUxXd3Iae4XIOb7guRqB",
	"+B/qvm47VdrNltfWsXEfZ3WXoDMOYbe+PLeKC1hft7delNcWKAi5Ipm/xH/qZw4n563cUhVuvq7YL9bI",
	"xv9V8qF67x0zrO298rtn1qf3R8Uc/ZxAOIXnI8KNNFQnal8RJiBtv4DvBeRc0GA9Tq39NMecam9rj55u",
	"ok6UJfoNI0Bfd4gVwS1eTIvO+Bd5yf3nJFZU+fzBw01r4WMT9YpDAGrak3AUpAVElRyr8LcEmEa2HYg0",
	"9aX7O4eZhk6uoAtzijTpaQ/IuC13coQhfKIpylyW5ZQAmXp0Me4w5xUl4Ac9j7NzdMuhrzccul/e/2LN",
	"rBwVc3+DIwkgMOWdYnlzi0zR7DzWX1vbe9b+U4oty8zgpR6ms7Ojk7E/L9qzK1jPM8RSxgUsc6qywLxf",
	"YUBfA0m9PfFvMYgRvIU47+2x1iQBHyT9oa9RvjqXHX9/p73QQISrA6xu5DlR8jbGLUVWaa6d3hijF9xf",
	"mpa+9wMh1vMHG0XLnD+Y+Y89OXtUzPXx41CCmsZwzCAESXKB0Bw6WN5/0KoWnbs1+xvCbN3tvcX3T3vr",
	"hbW763hY2t2qhx/zEeHDxie6XFqn30u2PYGNT2gIiiSq5BjNuNNPfoV9Mmn5JByHgqyIUEKM867vDhLj",
	"OIG8NyZrKNYd6Y6wmSuZ/wYAAP//FYDoBqMgAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
