//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Calendar defines model for Calendar.
type Calendar struct {
	// AliasCode URL上の識別子
	AliasCode string `json:"aliasCode"`

	// CoverImageUrl カバー画像 URL
	CoverImageUrl *string `json:"coverImageUrl,omitempty"`

	// Description カレンダーの概要文
	Description *string `json:"description,omitempty"`

	// Id カレンダーの一意識別子
	Id string `json:"id"`

	// SnsLinks 関連 SNS リンク
	SnsLinks *SNSLinks `json:"snsLinks,omitempty"`

	// Title カレンダー名（グループ/アイドル名）
	Title string `json:"title"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Detail エラー詳細メッセージ
	Detail string `json:"detail"`

	// Instance リクエストパス
	Instance *string `json:"instance,omitempty"`

	// Status HTTP ステータスコード
	Status int `json:"status"`

	// Title エラー概要
	Title string `json:"title"`

	// Type エラー種別 URI (RFC 7807)
	Type string `json:"type"`
}

// Event defines model for Event.
type Event struct {
	// AllDay 終日イベントフラグ
	AllDay bool `json:"allDay"`

	// Description イベント詳細・物販情報・チケット情報
	Description *string `json:"description,omitempty"`

	// EndAt 終了日時 (ISO8601)
	EndAt time.Time `json:"endAt"`

	// Id イベント一意識別子
	Id string `json:"id"`

	// ImageUrls 添付画像 URL リスト
	ImageUrls *[]string `json:"imageUrls,omitempty"`

	// Location 会場・開催場所
	Location *string `json:"location"`

	// StartAt 開始日時 (ISO8601)
	StartAt time.Time `json:"startAt"`

	// Timezone タイムゾーン（原則 Asia/Tokyo）
	Timezone string `json:"timezone"`

	// Title イベント名（公演・物販・生誕祭等）
	Title string `json:"title"`

	// Url 関連 URL（チケット・詳細ページ）
	Url *string `json:"url"`

	// Uuid イベント UUID
	Uuid *string `json:"uuid,omitempty"`
}

// EventListResponse defines model for EventListResponse.
type EventListResponse struct {
	Calendar   Calendar   `json:"calendar"`
	Events     []Event    `json:"events"`
	Pagination Pagination `json:"pagination"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
	Version   string    `json:"version"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	CurrentPage int `json:"currentPage"`
	TotalCount  int `json:"totalCount"`
	TotalPages  int `json:"totalPages"`
}

// SNSLinks 関連 SNS リンク
type SNSLinks struct {
	Instagram *string `json:"instagram,omitempty"`
	Twitter   *string `json:"twitter,omitempty"`
	Website   *string `json:"website,omitempty"`
}

// CalendarIdParam defines model for CalendarIdParam.
type CalendarIdParam = string

// BadGatewayError defines model for BadGatewayError.
type BadGatewayError = ErrorResponse

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorResponse

// GetCalendarEventsParams defines parameters for GetCalendarEvents.
type GetCalendarEventsParams struct {
	// Year 取得対象年（例: 2026）
	Year *int `form:"year,omitempty" json:"year,omitempty"`

	// Month 取得対象月 (1-12)
	Month *int `form:"month,omitempty" json:"month,omitempty"`

	// From 取得開始日 (YYYY-MM-DD)
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To 取得終了日 (YYYY-MM-DD)
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`

	// Page ページ番号
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCalendar request
	GetCalendar(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCalendarEvents request
	GetCalendarEvents(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCalendarEventsICS request
	GetCalendarEventsICS(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCalendar(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCalendarRequest(c.Server, calendarId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCalendarEvents(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCalendarEventsRequest(c.Server, calendarId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCalendarEventsICS(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCalendarEventsICSRequest(c.Server, calendarId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCalendarRequest generates requests for GetCalendar
func NewGetCalendarRequest(server string, calendarId CalendarIdParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "calendarId", runtime.ParamLocationPath, calendarId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/calendars/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCalendarEventsRequest generates requests for GetCalendarEvents
func NewGetCalendarEventsRequest(server string, calendarId CalendarIdParam, params *GetCalendarEventsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "calendarId", runtime.ParamLocationPath, calendarId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/calendars/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Year != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "year", runtime.ParamLocationQuery, *params.Year); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Month != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "month", runtime.ParamLocationQuery, *params.Month); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.From != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "from", runtime.ParamLocationQuery, *params.From); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.To != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "to", runtime.ParamLocationQuery, *params.To); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCalendarEventsICSRequest generates requests for GetCalendarEventsICS
func NewGetCalendarEventsICSRequest(server string, calendarId CalendarIdParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "calendarId", runtime.ParamLocationPath, calendarId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/calendars/%s/events.ics", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCalendarWithResponse request
	GetCalendarWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarResponse, error)

	// GetCalendarEventsWithResponse request
	GetCalendarEventsWithResponse(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*GetCalendarEventsResponse, error)

	// GetCalendarEventsICSWithResponse request
	GetCalendarEventsICSWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarEventsICSResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type GetCalendarResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Calendar
	JSON400      *BadRequestError
	JSON404      *NotFoundError
	JSON500      *InternalServerError
	JSON502      *BadGatewayError
}

// Status returns HTTPResponse.Status
func (r GetCalendarResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCalendarResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCalendarEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventListResponse
	JSON400      *BadRequestError
	JSON404      *NotFoundError
	JSON500      *InternalServerError
	JSON502      *BadGatewayError
}

// Status returns HTTPResponse.Status
func (r GetCalendarEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCalendarEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCalendarEventsICSResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequestError
	JSON404      *NotFoundError
	JSON500      *InternalServerError
	JSON502      *BadGatewayError
}

// Status returns HTTPResponse.Status
func (r GetCalendarEventsICSResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCalendarEventsICSResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCalendarWithResponse request returning *GetCalendarResponse
func (c *ClientWithResponses) GetCalendarWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarResponse, error) {
	rsp, err := c.GetCalendar(ctx, calendarId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCalendarResponse(rsp)
}

// GetCalendarEventsWithResponse request returning *GetCalendarEventsResponse
func (c *ClientWithResponses) GetCalendarEventsWithResponse(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*GetCalendarEventsResponse, error) {
	rsp, err := c.GetCalendarEvents(ctx, calendarId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCalendarEventsResponse(rsp)
}

// GetCalendarEventsICSWithResponse request returning *GetCalendarEventsICSResponse
func (c *ClientWithResponses) GetCalendarEventsICSWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarEventsICSResponse, error) {
	rsp, err := c.GetCalendarEventsICS(ctx, calendarId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCalendarEventsICSResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParseGetCalendarResponse parses an HTTP response from a GetCalendarWithResponse call
func ParseGetCalendarResponse(rsp *http.Response) (*GetCalendarResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCalendarResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Calendar
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGatewayError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetCalendarEventsResponse parses an HTTP response from a GetCalendarEventsWithResponse call
func ParseGetCalendarEventsResponse(rsp *http.Response) (*GetCalendarEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCalendarEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGatewayError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetCalendarEventsICSResponse parses an HTTP response from a GetCalendarEventsICSWithResponse call
func ParseGetCalendarEventsICSResponse(rsp *http.Response) (*GetCalendarEventsICSResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCalendarEventsICSResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGatewayError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// カレンダー基本情報の取得
	// (GET /api/v1/calendars/{calendarId})
	GetCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarIdParam)
	// イベント一覧の取得 (JSON)
	// (GET /api/v1/calendars/{calendarId}/events)
	GetCalendarEvents(w http.ResponseWriter, r *http.Request, calendarId CalendarIdParam, params GetCalendarEventsParams)
	// iCalendar (.ics) 形式でのイベント配信
	// (GET /api/v1/calendars/{calendarId}/events.ics)
	GetCalendarEventsICS(w http.ResponseWriter, r *http.Request, calendarId CalendarIdParam)
	// ヘルスチェック
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCalendar operation middleware
func (siw *ServerInterfaceWrapper) GetCalendar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", r.PathValue("calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendar(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCalendarEvents operation middleware
func (siw *ServerInterfaceWrapper) GetCalendarEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", r.PathValue("calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCalendarEventsParams

	// ------------- Optional query parameter "year" -------------

	err = runtime.BindQueryParameter("form", true, false, "year", r.URL.Query(), &params.Year)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		return
	}

	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameter("form", true, false, "month", r.URL.Query(), &params.Month)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendarEvents(w, r, calendarId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCalendarEventsICS operation middleware
func (siw *ServerInterfaceWrapper) GetCalendarEventsICS(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", r.PathValue("calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendarEventsICS(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/calendars/{calendarId}", wrapper.GetCalendar)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/calendars/{calendarId}/events", wrapper.GetCalendarEvents)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/calendars/{calendarId}/events.ics", wrapper.GetCalendarEventsICS)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RZW3PT2B3/KqramYWpYzkmCcFvbLhs2sBm4jAdusMwJ/axI9BtpeNAlvGMJW0Wh0BD",
	"GUiAMpOwkAuBmN2GLQEb8mGOpThP+QqdcyTLki1f2HZ52TdbOud////+F91gU7KoyBKUkMYmbrAKUIEI",
	"EVTpvxEgQCkN1NH0OHlOHqWhllJ5BfGyxCbYSV6EkyqEjDX36mBpARsvsfkKmzvYLGCzgvVSbfuhVVyz",
	"tu8eVopA4IF2OSWnIS7o1Y8LCYYX+Ay8LGcyfIoHwmFlno2wPKGrADTNRlgJiJBNsClPDDbCqvDbHK/C",
	"NJtAag5GWC01DUVARIPXgagI5EKQLhth0axCnmtI5aUsm8/nCR1NkSUNUkW/BOmzAMFrYPa0qsoqeZSS",
	"JQQlRH4CRRH4FCA6c1c0ovgNH9s/qTDDJtg/cg1Lcs5bjaPUJlxODt+gAbHxIzZNbC5j4x02i9jcInYz",
	"Vw8rxbptDyvzWN/Eeumg8Li69xQbm9h8Qa37EesrWH9dLT+wNx5az+ftf72xnz/ZX1lj8xGi0gT8Ngc1",
	"9LlVMrew8ZqI6ar0TyrvUyKysVfdvWNvPyMCjkoIqhIQklCdgepnt/sv1NB3sVmxfpg7MDc9uxLZzsvo",
	"jJyT0p9dqqb8cT1MTfqBGvAd1m/X1hew/hzrC9iYx/oW1r9nCS2XjT9xaUqrsgJVxDuRTpNwRE7D1mS+",
	"MDFW3b3lT1o28glJFWFT8gxUR0WQhRdUoZU+1Y4YfP9+2TIXmQsTYwEG0wgpWoLjAEIgNS0S00URL0Kk",
	"QggUJZqSRU7JTQl86nIdETiNXo5eUbJshM3IqggQm2BzKh8mX0CcG91sX7LXjdq6bi/dDJphjD9z+g9Y",
	"L2HjOTYf0QtFbJatm+/tyn3iIONnbOxic40G2Eusb2D9ES4YYRLx6V4Eqe4W7O8Xw70yMDRwbDiMtCZp",
	"Y7x0VesWlMnzSedcPsIiHgmwq0TW3TuHlSI2fiLaER2XOQJjxBzz2HxJX8+H2CwEh/1w/g2xRsQXoHV5",
	"Lnn35KkrMIWIpMFUaonyNESADw1BN8lrL3b23/xEUcnERpmm1m5A5nEaaUw90pgvgvH/BXMNaIwkIyZD",
	"gIKRJaYO2NFQT0saAlIqzLqteGm8C4jCAYXnZvq5uiwax0szQODTl6nFWl2PAMpprZy+mpwcZyiXHxww",
	"ptG6Q30YcNhAbMAjy0sIZqHaMTxcozoJExB9AmpyTk1B5ryMGAqpYQI7D9rS3d8sWcU15sLEKHNk4swI",
	"c3w4dvxoKHQIOZEncBFNwxkOkhjROElGfRmXc2eEaApH+rautWfVSD24QsNyxi0SzaArnAKzrRru/2LY",
	"y2tBIHlAdDZ+8quXAYIGPW5TsixAIPUAaA2y9XAv78+/qP37hW3OWas/Y7OMTZ3AFelAis7DgFmHufgg",
	"81faozh9yS17c8v+5QnWX2J93Zor1p7edihi455VWrGXPmB9mZatdogHpfRJFGqJ6vsf7OU1+5HBHBlN",
	"fj08FOsP+jgeiw/1xYb74oOT/fFELJaIxf4cO5GIxfx+TQME+0jR6B1tG1bqhLP98WMDg0PHQ6GWd0te",
	"SMrZb8vV8sNGwWNotpM8J60ugiK9061wuQ+AqoJZ8l+Qnf6jlV+18thafYPN8sHSgmW8slbf2POFgCIh",
	"7iSddk4QwBQ54HTVYZiiojDPEUYbC716jjrs0z1Hnn8nS6EgsUdduIqNj1SnncNK0frHijV/kzmp8YCb",
	"lK/Oys0FqfEmnFsbnGuEilMDrblXpObX04r8uL9S23qwv7a9vz3fzPTc6bMnaSFk/JlzWFkNd0mLWLmw",
	"pupg6ceDwjMSWqQm+9IZm+V61j92yluzPHXQRHzqKkTRaajKvAS16BWFE2EWkHLXS2Tkct3yirlwYfRU",
	"gPWJ4eNDgwPH4n1gKpXug5lYfx/Jr76h48MnyCPypLd2wYfOND7rCBOpg64veNoi9hivofbNRMrXTHfq",
	"pLymm8DcTH2i9pK842RA60ZIpisgy0ternciMd442WwoTwFPrgDhMLN8BYGAptvbpNFiNJwqX22XuhoC",
	"ohI87GFCfLJ/yMGEv/cMBzNQ1VyT+BA6GovGugaNV8XrNPwShlliPOCBpsjIqSqU0DjIwoAs/aHdk4yA",
	"MCLnnAahcTbe9jChq3Uj3Oxrn0gBMgEBwhT1BoF2GJM8n6Tly9zBxmsSQgFb0AY3626JWkHGe03HuO6z",
	"JLrGIwTVcGLXHSIETDsSuQanNB7BNhIRGfyoFxo7TWbK01Y+I3dYhdGJ/AXWS6E7Mbf1Mu5Zi0vWx2Vs",
	"lu3NR/b7Jev2EmmdCjozcTo5yZwcH2WwfgsbRazvMHwdWpgjUT6lHWXoQmgZ6+sHc3eqe09Ju2Us1Mof",
	"Dm4uYnMZm9vY2MbGW0LG6cMEPgXdRHaXaudGJ1m3pngmkRUoOf16VFaznHtJ48jZRl1k6102485InnRf",
	"qnw6CwlXX4LVMzMfYQl9oPBsgj0WjUWPURhC0zR8WmecG421X56cyMKQ7sO+fdMqPcb6A2zcxvpKk7FH",
	"T5GiWN+iMI0FJN2plcj4Z+w5HqETrdNKFMlcW9CdaQYXdKd7wwU9eT7pxb9T3xt+DLa9JDEoZoym2QR7",
	"FqKRBgT7V6zfhGN64wjXvILNX2paXcZjsf/bgqpRwbruphyrOcrbxbvWrRXi4AFHmDAentBc82aS3hvo",
	"fi+4lMtH2MFeuIWtGendeE+SBtbCdMuWE0WgzoasRVbe209eufmtlxzTEEwBWeJpbyensZcInc4BzzUa",
	"iF8R903bqepuoba+gY17uKC7DTrjNOzWhx+tyiLWN+ztZ7X1RQpCLknmL8mvzzMHc3es4rIHN58W7Kcb",
	"zcb/FPKRZu0dMazXH2s/P7XevTmsFOnnBNJT+D4ifJuD6mzjK8IspOkX8r2A3AsrrJ3Y2k+KzJH+vv74",
	"0TbsRFmi3zBC+A1HWBFc58Wc6JR/kZfcP71L4Y1dzJGLFy9e7Dt3ru/UqXayZFRZDBfF68OO9Td3X2Hl",
	"MFwWb3jvRRYkd5TkRF8s/msk8aac/Qdb1uLbNswVpy1qsE/DDMgJiJq+oxt+S9htnUFC8bc5oX/n4NuC",
	"b3XMZY4Q6Drqg14XiHrHXdJltcXes7KcFSDTjLnG98xJRQl5oZdw4Tbd/egbLZfu1fY+WLdWDyvFv8Gp",
	"FBCY2k6ltrVNeovCHay/tF5/tPaeUMRdYSbOjDCDgwODjP1+yV5YxXqJIZIyLoybN+tr3Xv1vvBTgHp0",
	"JPk52hMEryPOP1M3kiTkM23Q9I1GuEllR9/faS60jAdeWW9qBBwr+RPjuiKr1NdObkzTsf+7tqHv/2yK",
	"9dL+ZsUy7+zf+o89t3BYKY7xM1CCmsZwzAQEaTJWaU6TXNu73y0WnY0D+xvCbNNOo8tXYXv7mbW762hY",
	"3d1uhh/zIZkSjHd05bZBvyK99hk2OashKBKrkmvU404+BRmOySTl03AGCrIiQgkxztnAZJbgOIGcm5Y1",
	"lBiODcfY/KX8fwMAAP//U2q8nLkhAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
