//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Calendar defines model for Calendar.
type Calendar struct {
	// AliasCode URL上の識別子
	//
	// Example: ilife_official
	AliasCode string `json:"aliasCode"`

	// CoverImageUrl カバー画像 URL
	//
	// Example: https://attachments.timetreeapp.com/public_calendar/sample.jpg
	CoverImageUrl *string `json:"coverImageUrl,omitempty"`

	// Description カレンダーの概要文
	//
	// Example: iLiFE!のイベント・出演スケジュールです。
	Description *string `json:"description,omitempty"`

	// Id カレンダーの一意識別子
	//
	// Example: 46438
	Id string `json:"id"`

	// SnsLinks 関連 SNS リンク
	SnsLinks *SNSLinks `json:"snsLinks,omitempty"`

	// Title カレンダー名（グループ/アイドル名）
	//
	// Example: iLiFE!
	Title string `json:"title"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Detail エラー詳細メッセージ
	//
	// Example: Public calendar 'ilife_official' was not found on TimeTree.
	Detail string `json:"detail"`

	// Instance リクエストパス
	//
	// Example: /api/v1/calendars/invalid_id
	Instance *string `json:"instance,omitempty"`

	// Status HTTP ステータスコード
	//
	// Example: 404
	Status int `json:"status"`

	// Title エラー概要
	//
	// Example: Resource Not Found
	Title string `json:"title"`

	// Type エラー種別 URI (RFC 7807)
	//
	// Example: https://lumitree.dev/errors/not-found
	Type string `json:"type"`
}

// Event defines model for Event.
type Event struct {
	// AllDay 終日イベントフラグ
	//
	// Example: false
	AllDay bool `json:"allDay"`

	// Description イベント詳細・物販情報・チケット情報
	//
	// Example: 8/25 Kアリーナ横浜にて先行物販を実施します。
	Description *string `json:"description,omitempty"`

	// EndAt 終了日時 (ISO8601)
	//
	// Example: 2026-08-25T12:00:00+09:00
	EndAt time.Time `json:"endAt"`

	// Id イベント一意識別子
	//
	// Example: 12345678
	Id string `json:"id"`

	// ImageUrls 添付画像 URL リスト
	ImageUrls *[]string `json:"imageUrls,omitempty"`

	// Location 会場・開催場所
	//
	// Example: Kアリーナ横浜
	Location *string `json:"location,omitempty"`

	// StartAt 開始日時 (ISO8601)
	//
	// Example: 2026-08-25T09:00:00+09:00
	StartAt time.Time `json:"startAt"`

	// Timezone タイムゾーン（原則 Asia/Tokyo）
	//
	// Example: Asia/Tokyo
	Timezone string `json:"timezone"`

	// Title イベント名（公演・物販・生誕祭等）
	//
	// Example: MEGALiFE! 先行物販＠Kアリーナ横浜
	Title string `json:"title"`

	// Url 関連 URL（チケット・詳細ページ）
	//
	// Example: https://ticket.heroines.jp/megalife
	Url *string `json:"url,omitempty"`

	// Uuid イベント UUID
	//
	// Example: 98765432-abcd-ef01-2345-6789abcdef01
	Uuid *string `json:"uuid,omitempty"`
}

// EventListResponse defines model for EventListResponse.
type EventListResponse struct {
	Calendar   Calendar   `json:"calendar"`
	Events     []Event    `json:"events"`
	Pagination Pagination `json:"pagination"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`

	// Timestamp Example: 2026-08-22T16:00:00Z
	Timestamp time.Time `json:"timestamp"`

	// Version Example: 1.0.0
	Version string `json:"version"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// CurrentPage Example: 1
	CurrentPage int `json:"currentPage"`

	// TotalCount Example: 12
	TotalCount int `json:"totalCount"`

	// TotalPages Example: 1
	TotalPages int `json:"totalPages"`
}

// SNSLinks 関連 SNS リンク
type SNSLinks struct {
	// Instagram Example: https://instagram.com/ilife_official
	Instagram *string `json:"instagram,omitempty"`

	// Twitter Example: https://x.com/iLiFE_official
	Twitter *string `json:"twitter,omitempty"`

	// Website Example: https://ilife.heroines.jp
	Website *string `json:"website,omitempty"`
}

// CalendarIdParam Example: ilife_official
type CalendarIdParam = string

// BadGatewayError defines model for BadGatewayError.
type BadGatewayError = ErrorResponse

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorResponse

// GetCalendarEventsParams defines parameters for GetCalendarEvents.
type GetCalendarEventsParams struct {
	// Year 取得対象年（例: 2026）
	Year *int `form:"year,omitempty" json:"year,omitempty"`

	// Month 取得対象月 (1-12)
	Month *int `form:"month,omitempty" json:"month,omitempty"`

	// Page ページ番号
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetCalendar カレンダー基本情報の取得
	//
	// 指定されたカレンダーID（または alias_code）のメタ情報（タイトル、概要、画像、SNSリンク等）を取得します。.
	//
	// Corresponds with GET /api/v1/calendars/{calendarId} (the `GetCalendar` operationId).
	GetCalendar(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCalendarEvents イベント一覧の取得 (JSON)
	//
	// 指定されたカレンダーのイベント一覧を、ISO8601 日時形式で正規化された JSON 配列として取得します。.
	//
	// Corresponds with GET /api/v1/calendars/{calendarId}/events (the `GetCalendarEvents` operationId).
	GetCalendarEvents(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCalendarEventsICS iCalendar (.ics) 形式でのイベント配信
	//
	// Google カレンダーや Apple カレンダーの「URL でカレンダーを追加（Webcal 購読）」に対応した RFC 5545 準拠の .ics 形式データを配信します。
	//
	// Corresponds with GET /api/v1/calendars/{calendarId}/events.ics (the `GetCalendarEventsICS` operationId).
	GetCalendarEventsICS(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth ヘルスチェック
	//
	// サーバーの稼働状態（Liveness / Readiness）を返します。.
	//
	// Corresponds with GET /healthz (the `GetHealth` operationId).
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetCalendar カレンダー基本情報の取得
//
// 指定されたカレンダーID（または alias_code）のメタ情報（タイトル、概要、画像、SNSリンク等）を取得します。.
//
// Corresponds with GET /api/v1/calendars/{calendarId} (the `GetCalendar` operationId).
func (c *Client) GetCalendar(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCalendarRequest(c.Server, calendarId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetCalendarEvents イベント一覧の取得 (JSON)
//
// 指定されたカレンダーのイベント一覧を、ISO8601 日時形式で正規化された JSON 配列として取得します。.
//
// Corresponds with GET /api/v1/calendars/{calendarId}/events (the `GetCalendarEvents` operationId).
func (c *Client) GetCalendarEvents(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCalendarEventsRequest(c.Server, calendarId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetCalendarEventsICS iCalendar (.ics) 形式でのイベント配信
//
// Google カレンダーや Apple カレンダーの「URL でカレンダーを追加（Webcal 購読）」に対応した RFC 5545 準拠の .ics 形式データを配信します。
//
// Corresponds with GET /api/v1/calendars/{calendarId}/events.ics (the `GetCalendarEventsICS` operationId).
func (c *Client) GetCalendarEventsICS(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCalendarEventsICSRequest(c.Server, calendarId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHealth ヘルスチェック
//
// サーバーの稼働状態（Liveness / Readiness）を返します。.
//
// Corresponds with GET /healthz (the `GetHealth` operationId).
func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCalendarRequest constructs an http.Request for the GetCalendar method
func NewGetCalendarRequest(server string, calendarId CalendarIdParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "calendarId", calendarId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/calendars/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCalendarEventsRequest constructs an http.Request for the GetCalendarEvents method
func NewGetCalendarEventsRequest(server string, calendarId CalendarIdParam, params *GetCalendarEventsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "calendarId", calendarId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/calendars/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Year != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "year", *params.Year, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Month != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "month", *params.Month, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCalendarEventsICSRequest constructs an http.Request for the GetCalendarEventsICS method
func NewGetCalendarEventsICSRequest(server string, calendarId CalendarIdParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "calendarId", calendarId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/calendars/%s/events.ics", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest constructs an http.Request for the GetHealth method
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetCalendarWithResponse カレンダー基本情報の取得
	//
	// 指定されたカレンダーID（または alias_code）のメタ情報（タイトル、概要、画像、SNSリンク等）を取得します。.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/calendars/{calendarId} (the `GetCalendar` operationId).
	GetCalendarWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarResponse, error)

	// GetCalendarEventsWithResponse イベント一覧の取得 (JSON)
	//
	// 指定されたカレンダーのイベント一覧を、ISO8601 日時形式で正規化された JSON 配列として取得します。.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/calendars/{calendarId}/events (the `GetCalendarEvents` operationId).
	GetCalendarEventsWithResponse(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*GetCalendarEventsResponse, error)

	// GetCalendarEventsICSWithResponse iCalendar (.ics) 形式でのイベント配信
	//
	// Google カレンダーや Apple カレンダーの「URL でカレンダーを追加（Webcal 購読）」に対応した RFC 5545 準拠の .ics 形式データを配信します。
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/calendars/{calendarId}/events.ics (the `GetCalendarEventsICS` operationId).
	GetCalendarEventsICSWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarEventsICSResponse, error)

	// GetHealthWithResponse ヘルスチェック
	//
	// サーバーの稼働状態（Liveness / Readiness）を返します。.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /healthz (the `GetHealth` operationId).
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type GetCalendarResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Calendar
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequestError
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFoundError
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
	// JSON502 the response for an HTTP 502 `application/json` response
	JSON502 *BadGatewayError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCalendarResponse) GetJSON200() *Calendar {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetCalendarResponse) GetJSON400() *BadRequestError {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetCalendarResponse) GetJSON404() *NotFoundError {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetCalendarResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetJSON502 returns the response for an HTTP 502 `application/json` response
func (r GetCalendarResponse) GetJSON502() *BadGatewayError {
	return r.JSON502
}

// GetBody returns the raw response body bytes
func (r GetCalendarResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCalendarResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCalendarResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCalendarResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCalendarEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *EventListResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequestError
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFoundError
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
	// JSON502 the response for an HTTP 502 `application/json` response
	JSON502 *BadGatewayError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCalendarEventsResponse) GetJSON200() *EventListResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetCalendarEventsResponse) GetJSON400() *BadRequestError {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetCalendarEventsResponse) GetJSON404() *NotFoundError {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetCalendarEventsResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetJSON502 returns the response for an HTTP 502 `application/json` response
func (r GetCalendarEventsResponse) GetJSON502() *BadGatewayError {
	return r.JSON502
}

// GetBody returns the raw response body bytes
func (r GetCalendarEventsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCalendarEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCalendarEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCalendarEventsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCalendarEventsICSResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequestError
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFoundError
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
	// JSON502 the response for an HTTP 502 `application/json` response
	JSON502 *BadGatewayError
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetCalendarEventsICSResponse) GetJSON400() *BadRequestError {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetCalendarEventsICSResponse) GetJSON404() *NotFoundError {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetCalendarEventsICSResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetJSON502 returns the response for an HTTP 502 `application/json` response
func (r GetCalendarEventsICSResponse) GetJSON502() *BadGatewayError {
	return r.JSON502
}

// GetBody returns the raw response body bytes
func (r GetCalendarEventsICSResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCalendarEventsICSResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCalendarEventsICSResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCalendarEventsICSResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *HealthResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetHealthResponse) GetJSON200() *HealthResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetCalendarWithResponse カレンダー基本情報の取得
//
// 指定されたカレンダーID（または alias_code）のメタ情報（タイトル、概要、画像、SNSリンク等）を取得します。.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/calendars/{calendarId} (the `GetCalendar` operationId).
func (c *ClientWithResponses) GetCalendarWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarResponse, error) {
	rsp, err := c.GetCalendar(ctx, calendarId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCalendarResponse(rsp)
}

// GetCalendarEventsWithResponse イベント一覧の取得 (JSON)
//
// 指定されたカレンダーのイベント一覧を、ISO8601 日時形式で正規化された JSON 配列として取得します。.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/calendars/{calendarId}/events (the `GetCalendarEvents` operationId).
func (c *ClientWithResponses) GetCalendarEventsWithResponse(ctx context.Context, calendarId CalendarIdParam, params *GetCalendarEventsParams, reqEditors ...RequestEditorFn) (*GetCalendarEventsResponse, error) {
	rsp, err := c.GetCalendarEvents(ctx, calendarId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCalendarEventsResponse(rsp)
}

// GetCalendarEventsICSWithResponse iCalendar (.ics) 形式でのイベント配信
//
// Google カレンダーや Apple カレンダーの「URL でカレンダーを追加（Webcal 購読）」に対応した RFC 5545 準拠の .ics 形式データを配信します。
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/calendars/{calendarId}/events.ics (the `GetCalendarEventsICS` operationId).
func (c *ClientWithResponses) GetCalendarEventsICSWithResponse(ctx context.Context, calendarId CalendarIdParam, reqEditors ...RequestEditorFn) (*GetCalendarEventsICSResponse, error) {
	rsp, err := c.GetCalendarEventsICS(ctx, calendarId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCalendarEventsICSResponse(rsp)
}

// GetHealthWithResponse ヘルスチェック
//
// サーバーの稼働状態（Liveness / Readiness）を返します。.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /healthz (the `GetHealth` operationId).
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParseGetCalendarResponse parses an HTTP response from a GetCalendarWithResponse call
func ParseGetCalendarResponse(rsp *http.Response) (*GetCalendarResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCalendarResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Calendar
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGatewayError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetCalendarEventsResponse parses an HTTP response from a GetCalendarEventsWithResponse call
func ParseGetCalendarEventsResponse(rsp *http.Response) (*GetCalendarEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCalendarEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGatewayError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetCalendarEventsICSResponse parses an HTTP response from a GetCalendarEventsICSWithResponse call
func ParseGetCalendarEventsICSResponse(rsp *http.Response) (*GetCalendarEventsICSResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCalendarEventsICSResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest BadGatewayError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetCalendar カレンダー基本情報の取得
	// (GET /api/v1/calendars/{calendarId})
	GetCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarIdParam)
	// GetCalendarEvents イベント一覧の取得 (JSON)
	// (GET /api/v1/calendars/{calendarId}/events)
	GetCalendarEvents(w http.ResponseWriter, r *http.Request, calendarId CalendarIdParam, params GetCalendarEventsParams)
	// GetCalendarEventsICS iCalendar (.ics) 形式でのイベント配信
	// (GET /api/v1/calendars/{calendarId}/events.ics)
	GetCalendarEventsICS(w http.ResponseWriter, r *http.Request, calendarId CalendarIdParam)
	// GetHealth ヘルスチェック
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCalendar operation middleware
func (siw *ServerInterfaceWrapper) GetCalendar(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", r.PathValue("calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendar(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCalendarEvents operation middleware
func (siw *ServerInterfaceWrapper) GetCalendarEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", r.PathValue("calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCalendarEventsParams

	// ------------- Optional query parameter "year" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "year", r.URL.Query(), &params.Year, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "month", r.URL.Query(), &params.Month, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "month"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendarEvents(w, r, calendarId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCalendarEventsICS operation middleware
func (siw *ServerInterfaceWrapper) GetCalendarEventsICS(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", r.PathValue("calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendarEventsICS(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/calendars/{calendarId}", wrapper.GetCalendar)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/calendars/{calendarId}/events", wrapper.GetCalendarEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/calendars/{calendarId}/events.ics", wrapper.GetCalendarEventsICS)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FlrUxNZGv4rvb1bNVob0iECYr45eBl2GYYiUFu1U5Z1SA6htW92n6CMlap0t0i4La6loK5V4IWLKEEX",
	"XdFE+DEn3YRP/IWtc7qTdCcdgrszfplv0Onz3t/nfc7bt9mELCqyBCWksbHbrAJUIEIEVfpfDxCglARq",
	"b3KAPCePklBLqLyCeFliY+wQL8IhFULGmnxzuDiLjdfYfIPNHWxmsVnEer689cjKrVpb946KOSDwQLua",
	"kJMQZ/XS3myM4QV+FF6VR0f5BA+Eo+I0G2J5IlcBaIwNsRIQIRtjE1Uz2BCrwhtpXoVJNobUNAyxWmIM",
	"ioCYBm8BURHIAb9cNsSiCYU815DKSyk2k8kQOZoiSxqkjn4PkpcBgjfBxEVVlVXyKCFLCEqI/AkUReAT",
	"gPjMXdOI47c9av+kwlE2xv6Rq0WSc37VOCpt0NXk6PUHEBvPsWlicwkbn7CZw+YmiZu5clTMVWJ7VJzG",
	"+gbW84fZJ6X9Z9jYwOYrGt09rC9jfbtUeGivP7JeTtv/em+/fHqwvMpmQsSlQXgjDTX0rV0yN7GxTcx0",
	"XfontfcZMdnYL+3O21sviIG9EoKqBIQ4VMeh+s3j/oEG+h42i9bdyUNzoxpXYlu/jC7JaSn5za2q6x83",
	"wzSkX2gAP2F9rrw2i/WXWJ/FxjTWN7F+hyWyXDXexqUtrcoKVBHvVDptwh45CRubeXiwr7Q7421aNvQV",
	"TRViE/I4VHtFkILDqtAon3pHAn7woGCZC8zwYJ9PwRhCihbjOIAQSIyJJHRhxIsQqRACRQknZJFT0iMC",
	"n7haQQROo4fD15QUG2JHZVUEiI2xaZUPss9nzu1Wsc/ba0Z5TbcXp/xh6OMvXfwD1vPYeInNx/RADpsF",
	"a+qzXXxAEmS8w8YuNldpgb3G+jrWH+OsEWQRnzyJIaXdrH1nITgrHV0dZ7qDRGuS1sdL17VWRRnvjzvv",
	"ZUIs4pEAW1pk3Zs/Kuaw8ZZ4R3xc4giMkXBMY/M1/Xk6IGYBOOyF859JNEKeAq3Yc6V6Th65BhOIWOpv",
	"pYYqT0IE+MASdJu8/Grn4P1bikomNgq0tXZ9Ng/QSmMqlcZ856//75ibQGMkGTGjBCgYWWIqgB0OzLSk",
	"ISAlgqLbiJfGJ58pHFB4brydq9iicbw0DgQ+eZVGrDH1CKC01qjph6GhAYZqueuAMa3WHZpDX8I6Ih1V",
	"sbyEYAqqx5aHG1SnYXymD0JNTqsJyPTLiKGQGmSw86Cp3IONvJVbZYYHe5lTg5d6mLPdkbOnA6FDSIs8",
	"gYtwEo5zkNSIxkkyaht1NR+PEHXlSH+teF2NaqhSXIFlOe4OiXrQFS6AiUYPDz4Y9tKqH0geEp+Nt173",
	"RoGgwaq2EVkWIJBOAGg1sZVyLxxMvyr/+5VtTlor77BZwKZO4IowkJzz0BfWbi7ayfyVchSHl8zYG5v2",
	"h6dYf431NWsyV34250jExn0rv2wvfsH6Eh1bzRAPSsnzKDASpc937aVV+7HBnOqN/9TdFWn35zgaiXa1",
	"Rbrbop1D7dFYJBKLRP4cOReLRLx5TQIE28jQODna1qJ0HM62R890dHadDYRa3h15AS1nfyyUCo9qA4+h",
	"3U76nFBdBEV6ptXgch8AVQUT5H9BdvhHo75S8Ym18h6bhcPFWct4Y628t6ezPkcC0kmYdloQwAh5wWHV",
	"QZiioqDMEUXrsyfNHE3Y12eOPP9FlgJBYp+mcAUbe9SnnaNizvrHsjU9xZzXeMANydcn5PqBVPslWFsT",
	"nKuVijMDrck3ZOZX2or88WC5vPnwYHXrYGu6XumPFy+fp4OQ8XbOUXElOCUNZqWDSNXh4vPD7AtSWmQm",
	"e9oZm4VK1z9xxlu9PRXQRHziOkThMajKvAS18DWFE2EKkHF3kspIp1v1FTM83HvBp/pc99muzo4z0TYw",
	"kki2wdFIexvpr7aus93nyCPy5GR0wYPOtD4rCBOqgK6neJoidh+voeZkIuEh08cxqSrpJjA3XrlRV5v8",
	"2JsBnRsBna6AFC9Ve/04EQO1N+sDVXWgapdPcFBYfoBAQGPNY1KjGLWkytebta6GgKj4X65iQnSovcvB",
	"hL+fGA7Goaq5IfEgdDgSjrQsmuoUr8jwWhgUiQFfBuoqI62qUEIDIAV9trQHsicZAaFHTjsEofZutOnL",
	"RK7WSnB9rj0m+cT4DAhytHoRaIYx8f44HV/mDja2SQn5YkEJbsrdEjWCTPVneo1rfZdEN3mEoBos7JYj",
	"hIDpsUJuwhGNR7CJRcQGL+oF1k5dmDKUyo/Kx6zC6I38FdbzgTsxl3oZ962FRWtvCZsFe+Ox/XnRmlsk",
	"1CmrM4MX40PM+YFeBusz2MhhfYfhK9DCnArzCe00QxdCS1hfO5ycL+0/I3TLmC0XvhxOLWBzCZtb2NjC",
	"xkcixuFhAp+AbiO7S7Ufe4dYd6ZUQyIrUHL4elhWU5x7SOPIu7W5yFZYNuPekarWfa/yyRQkWj0NVunM",
	"TIgl8oHCszH2TDgSPkNhCI3R8mm849yurf0y5I0UDGAf9tyUlX+C9YfYmMP6cl2wey+QoVjZojC1BSTd",
	"qeXJ9c/YdzJCb7QOlciRe21Wd24zOKs77A1n9Xh/vFr/znyv5dFPe0ljUMzoTbIx9jJEPTUI9q5Yfw7G",
	"9NorXP0KNnOlbnUZjUR+tQVVbYK13E05UXOct3P3rJllkuAOx5ggHVWjufrNJD3X0fqcfymXCbGdJ9EW",
	"tGakZ6MnstS3FqZbtrQoAnUiYC2y/Nl++sbtbz3vhIZgCkiRTFd3chp7hcg5vuC5GoH4H+q+bjtV2s2W",
	"19axcR9ndZegMw5ht748t4oLWF+3t16U1xYoCLkimb/Ef+pnDifnrdxSFW6+rtgv1sjG/1XyoXrvHTOs",
	"7b3yu2fWp/dHxRz9nEA4hecjwo00VCdqXxEmIG2/gO8F5FzQYD1Orf00x5xqb2uPnm6iTpQl+g0jQF93",
	"iBXBLV5Mi874F3nJ/eckVlT5/MHDTWvhYxP1ikMAatqTcBSkBUSVHKvwtwSYRrYdiDT1pfs7h5mGTq6g",
	"C3OKNOlpD8i4LXdyhCF8oinKXJbllACZenQx7jDnFSXgBz2Ps3N0y6GvNxy6X97/Ys2sHBVzf4MjCSAw",
	"5Z1ieXOLTNHsPNZfW9t71v5Tii3LzOClHqazs6OTsT8v2rMrWM8zxFLGBSxzqrLAvF9hQF8DSb098W8x",
	"iBG8hTjv7bHWJAEfJP2hr1G+Opcdf3+nvdBAhKsDrG7kOVHyNsYtRVZprp3eGKMX3F+alr73AyHW8wcb",
	"RcucP5j5jz05e1TM9fHjUIKaxnDMIARJcoHQHDpY3n/QqhaduzX7G8Js3e29xfdPe+uFtbvreFja3aqH",
	"H/MR4cPGJ7pcWqffS7Y9gY1PaAiKJKrkGM24009+hX0yafkkHIeCrIhQQozzru8OEuM4gbw3Jmso1h3p",
	"jrCZK5n/BgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
