apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumitree
  labels:
    app.kubernetes.io/name: lumitree
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: lumitree.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lumitree
                port:
                  number: 8080
