apiVersion: v1
kind: Service
metadata:
  name: lumitree
  namespace: lumitree
  labels:
    app: lumitree
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: lumitree
